version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-17-151.compute-1.amazonaws.com
            port: '5432'
            database: d6gvnpb7pudvnt
            ssl: true
            user: uajwuxbmihvsyh
            password: 292a0885ce65e80839ce84eb01e8e39dff0c310e0a345191b6dfcb73d50aa51d
            migrations: true